BoxLayout:
    orientation: 'horizontal'


    BoxLayout:
        orientation: 'vertical'
        Label:
            id: output_label1
            font_size: 48
            color: (1, 0, 0, 1)
        TextInput:
            id: text_input1
            multiline: False
        TextInput:
            id: text_input2
            multiline: False
        TextInput:
            id: text_input3
            multiline: False


    BoxLayout:
        orientation: 'vertical'
        Label:
            id: output_label2
            font_size: 48
            color: (1, 0, 0, 1)
        BoxLayout:
            orientation: 'horizontal'
            TextInput:
                id: text_input1
                multiline: False
            TextInput:
                id: text_input1
                multiline: False
        TextInput:
            id: text_input5
            multiline: False
        TextInput:
            id: text_input6
            multiline: False
