BoxLayout:
    orientation: 'horizontal'


    BoxLayout:
        orientation: 'vertical'
        Label:
            id: output_label1
            font_size: 48
            color: (1, 0, 0, 1)
        Spinner:
            # text_autoupdate sets the text to the first value of the values property
            text_autoupdate: True
            # values takes a list - could be a literal here or variable in app
            values: app.state_codes
            # on_text is the event (not on_release) when the text updates (spinner option is selected)
            # note that on_text runs even when the text is set for the very first time
            on_text: app.change_state(self.text)
        TextInput:
            id: text_input2
            multiline: False
        TextInput:
            id: text_input3
            multiline: False


    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            Label:
                id: output_label2
                font_size: 48
                text: "wwwww"
                color: (1, 0, 0, 1)
            Label:
                id: output_label3
                font_size: 48
                text: "wwwww"
                color: (1, 0, 0, 1)
        TextInput:
            id: text_input4
            multiline: False
        TextInput:
            id: text_input5
            multiline: False
        TextInput:
            id: text_input6
            multiline: False