BoxLayout:
    orientation: 'horizontal'


    BoxLayout:
        orientation: 'vertical'
        TextInput:
            id: text_input1
            multiline: False
        TextInput:
            id: text_input2
            multiline: False
        TextInput:
            id: text_input3
            multiline: False


    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            TextInput:
                id: text_input1
                multiline: False
            TextInput:
                id: text_input1
                multiline: False
        TextInput:
            id: text_input5
            multiline: False
        TextInput:
            id: text_input6
            multiline: False
